# Generated by Django 4.2.9 on 2024-02-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('date_created', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
